import React,{useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';
import Library from './library/Library.jsx';
import Dashboard from './dashboard/Dashboard.jsx';
import Coach from './coach/Coach.jsx';
import News from './news/News.jsx';
const KEY='offergo-profile-draft-v1';
const empty={school:'',major:'',grade:'',language:'',tests:'尚未参加',intake:'2027 Fall',direction:'EE · 电子与电气',rank:'QS 前50',city:'不限',cross:'否',internships:'0',research:'0'};
const demo={...empty,school:'海川理工大学（虚构）',major:'电气工程及其自动化',grade:'82/100',language:'尚未参加',internships:'1',research:'1'};
const titles=['申请动机','课程与项目','实习与科研','贡献与成长','未来规划'];
function question(i,f){const direction=f.direction.split(' · ')[0];return [
`你希望申请 ${f.intake} 的 ${direction} 方向。是什么具体的课程、问题或经历，让你想继续学习这个方向？`,
`请选一段与 ${direction} 相关的课程项目，讲清：当时的背景（S）、你的任务（T）、你采取的行动（A）、最后的结果（R）。不需要很出色，真实、具体就好。`,
parseInt(f.internships)+parseInt(f.research)>0?`你填写了 ${f.internships} 段实习、${f.research} 段科研。选最相关的一段，说说你承担的任务、实际行动和收获；没有可分享的部分也可以直接说明。`:'如果暂时没有实习或科研，可以讲一段自学、社团或第二个课程项目。你投入了什么，遇到了什么困难？',
'回看刚才的经历，哪些工作由你独立完成，哪些是团队合作？请讲一个困难，以及你如何调整方法、从中学到了什么。',
'读完硕士后，你短期想从事什么工作或继续什么研究？长期想解决什么问题？你最希望硕士课程帮助你补齐哪项能力？'
][i]}
const sampleAnswers=['在电力系统课程里，我第一次尝试分析配电网络中的电压波动。我想进一步学习电网控制与稳定性，也希望把课堂模型用于实际工程。','背景：课程要求分析一个小型配电网络。\n任务：我负责比较不同负载下的电压变化。\n行动：搭建仿真模型，检查参数，并和队友一起分析异常结果。\n结果：完成课程报告，认识到模型假设会影响结论。','在一家虚构的设备企业实习时，我协助整理测试记录并检查缺失字段；科研体验主要是阅读电网稳定性资料。这些经历都还比较初步。','仿真模型的初版和参数检查由我完成，报告由小组共同完成。最初结果异常，我逐项核对单位和负载设置，修正后重新测试。我学会了先检查假设，再解释结果。','短期：希望从事电力系统分析相关工作。\n长期：参与更可靠的配电系统建设。\n能力缺口：系统建模、控制理论与工程验证。'];
function loadSaved(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v?.version===1&&v.form&&Array.isArray(v.answers)&&v.answers.length<=5)return v;}catch{}return null;}
function App(){const [route,setRoute]=useState(location.hash.slice(1)||'home');const [form,setForm]=useState(empty);const [answers,setAnswers]=useState([]);const [input,setInput]=useState('');const [saved,setSaved]=useState(loadSaved);const [busy,setBusy]=useState(false);const [toast,setToast]=useState('');const [service,setService]=useState('schools');const [draft,setDraft]=useState('');const [refresh,setRefresh]=useState(0);const feed=useRef(null);const timer=useRef(null);
useEffect(()=>{const cb=()=>setRoute(location.hash.slice(1)||'home'),r=()=>setRefresh(x=>x+1);window.addEventListener('hashchange',cb);window.addEventListener('offergo-refresh',r);return()=>{window.removeEventListener('hashchange',cb);window.removeEventListener('offergo-refresh',r);clearTimeout(timer.current)}},[]);
useEffect(()=>{window.scrollTo(0,0);document.querySelectorAll('nav a').forEach(a=>{const match=a.hash==='#'+(['interview','profile','advice'].includes(route)?'match':route.startsWith('university/')||route.startsWith('program/')?'programs':route);a.classList.toggle('active',match);if(match)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')})},[route]);
useEffect(()=>{feed.current?.scrollTo({top:feed.current.scrollHeight,behavior:'smooth'})},[answers,busy,route]);
useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),4200);return()=>clearTimeout(t)}},[toast]);
const isLibrary=route==='programs'||route.startsWith('university/')||route.startsWith('program/');
const isDashboard=route==='applications';
const isNews=route==='guides';
useEffect(()=>{document.body.classList.toggle('is-library',isLibrary);document.body.classList.toggle('is-news',isNews);return()=>{document.body.classList.remove('is-library');document.body.classList.remove('is-news')}},[isLibrary,isNews]);
const go=p=>{location.hash=p};const notify=s=>setToast(s);
function saveExit(){try{const v={version:1,form,answers,input,date:new Date().toLocaleString('zh-CN')};localStorage.setItem(KEY,JSON.stringify(v));setSaved(v);go('match');notify('草稿已保存在当前浏览器，可随时继续。')}catch{notify('浏览器未允许保存，请保持页面打开，当前内容仍在。')}}
function resume(){if(!saved)return;setForm({...empty,...saved.form});setAnswers(saved.answers);setInput(saved.input||'');go(saved.answers.length===5?'profile':'interview')}
function send(e){e.preventDefault();if(!input.trim()||busy||answers.length>=5)return;const text=input.trim();setAnswers(a=>[...a,text]);setInput('');setBusy(true);timer.current=setTimeout(()=>setBusy(false),500)}
const star=()=>{const text=answers[1]||'';return ['背景','任务','行动','结果'].map((k,i)=>{const m=text.match(new RegExp('(?:^|\\n)'+k+'[：:]\\s*([^\\n]*)'));return [k,m?.[1]||'待补充：请从原始经历中确认这一部分。']})};
const outline=()=>`PS 核心提纲（前端模拟，待本人确认）\n目标方向：${form.direction}\n\n1. 学术动机\n${answers[0]||'待补充'}\n\n2. 相关项目与能力证据\n${answers[1]||'待补充'}\n\n3. 实习 / 科研 / 其他经历\n${answers[2]||'待补充'}\n\n4. 个人贡献与反思\n${answers[3]||'待补充'}\n\n5. 职业目标与能力缺口\n${answers[4]||'待补充'}\n\n6. 为什么选择具体项目\n待核对官网课程与PS题目后补充，不自动编写学校匹配理由。`;
function openService(s){setService(s);go('advice')}
const hasProfile=answers.length===5;
function Stepper({step}){return <div className="og-steps" aria-label="建档流程">{['基础信息','深度访谈','申请档案','专属建议'].map((s,i)=><div key={s} className={i===step?'current':i<step?'complete':''}><span>{i<step?'✓':`0${i+1}`}</span><b>{s}</b></div>)}</div>}
function Banner(){return <div className="og-notice"><span>前端模拟</span>访谈采用预设问题与规则整理，不调用真实 AI，不上传信息。示例人物与经历均为虚构。</div>}
function ActionButton({children,onClick,secondary=false}){return <button className={secondary?'btn':'btn primary'} onClick={onClick}>{children}</button>}
if(isLibrary)return <Library route={route}/>;
if(isDashboard)return <Dashboard/>;
if(route==='coach')return <><Coach draft={draft} notify={notify}/>{toast&&<div className="og-toast" role="status">{toast}</div>}</>;
if(route==='guides')return <News/>;
if(!['match','interview','profile','advice'].includes(route))return <><Legacy route={route} refresh={refresh} draft={draft}/>{toast&&<div className="og-toast" role="status">{toast}</div>}</>;
return <div className="og-flow"><div className="flex flex-wrap items-center justify-between gap-3 mb-6"><a href="#home" className="text-sm text-slate-500">OfferGo / 选校与申请档案</a><span className="og-kicker">YOUR STORY. YOUR NEXT CHAPTER.</span></div><Stepper step={['match','interview','profile','advice'].indexOf(route)}/>
{route==='match'&&<><div className="og-title"><span className="og-kicker">01 / BUILD YOUR FOUNDATION</span><h1>先了解你，再谈适合的选择。</h1><p>成绩是起点，你的经历与目标让申请更完整。用一份档案，连接选校、时间线和文书。</p></div><Banner/>{saved&&<div className="og-saved"><div><strong>你有一份本机草稿</strong><small>保存于 {saved.date} · 仅在此浏览器可用</small></div><button className="btn primary" onClick={resume}>继续建档</button><button className="btn" onClick={()=>{try{localStorage.removeItem(KEY);setSaved(null);notify('本机草稿已删除。')}catch{notify('删除失败，请检查浏览器设置。')}}}>删除本机草稿</button></div>}
<div className="grid lg:grid-cols-[1fr_310px] gap-7 items-start"><form className="og-panel" onSubmit={e=>{e.preventDefault();go('interview')}}><div className="flex justify-between gap-4 items-start mb-7"><div><h2>基础信息</h2><p className="text-sm text-slate-500 mt-1">先记录硬指标，再通过访谈补充故事。</p></div><button type="button" className="og-link" onClick={()=>{setForm(demo);notify('已填入虚构示例；你的真实资料不会自动带入。')}}>填入虚构示例</button></div><div className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-5">{[['school','本科学校','请输入学校名称'],['major','本科专业','例如：电气工程及其自动化'],['grade','均分 / GPA','填写数值及满分制，例如 82/100'],['language','语言成绩','可填写“尚未参加”']].map(([k,l,ph])=><label key={k} className="og-field">{l}<span className="text-amber-700"> *</span><input required maxLength={120} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={ph}/></label>)}{[['tests','GMAT / GRE 情况',['尚未参加','计划参加','已参加（访谈中补充）','不适用']],['intake','目标入学季',['2027 Fall','2028 Fall','2029 Fall','尚未确定']],['direction','目标方向',['EE · 电子与电气','CS · 计算机','Business · 商科','其他 / 尚未确定']],['rank','院校排名偏好',['QS 前50','QS 前100','QS 前200','专业匹配优先']],['city','城市偏好',['不限','伦敦','曼彻斯特','其他城市']],['cross','是否跨专业',['否','是','尚未确定']],['internships','实习数量',['0','1','2','3','4及以上']],['research','科研数量',['0','1','2','3','4及以上']]].map(([k,l,opts])=><label key={k} className="og-field">{l}<select value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}>{opts.map(o=><option key={o}>{o}</option>)}</select></label>)}</div><div className="og-form-bottom"><p>默认仅在当前页面中处理，不上传；只有点击“保存并退出”才会保存到本机。</p><button className="btn primary" type="submit">{answers.length?'返回深度访谈':'提交并进入 AI 深度访谈'}</button></div></form><aside className="og-aside"><span className="og-kicker">MORE THAN A SCORE</span><h2>把“我做过”<br/>变成“我能证明”。</h2><div className="og-aside-row"><b>01</b><div><strong>先收集事实</strong><p>学校、课程、成绩和申请偏好。</p></div></div><div className="og-aside-row"><b>02</b><div><strong>再挖掘经历</strong><p>任务、行动、结果和你的贡献。</p></div></div><div className="og-aside-row"><b>03</b><div><strong>留下可复用的档案</strong><p>选校有依据，文书有素材。</p></div></div><p className="text-sm border-t border-slate-300 pt-5">不需要先把经历写漂亮。具体、真实，比“优秀”“热爱”更有价值。</p></aside></div></>}
{route==='interview'&&<>{!form.school?<Empty text="请先填写基础信息，让访谈有一个起点。" go={()=>go('match')}/>:<><div className="og-title"><span className="og-kicker">02 / DISCOVER YOUR STORY</span><h1>一起找到，值得讲述的经历。</h1><p>不用写成文书。把发生过的事情告诉我们，就从一段经历开始。</p></div><Banner/><div className="grid lg:grid-cols-[250px_1fr] gap-6 items-start"><aside className="og-panel og-module-panel"><span className="og-kicker">访谈进度 {Math.min(answers.length+1,5)} / 5</span><div className="og-track"><i style={{width:answers.length/5*100+'%'}}/></div>{titles.map((t,i)=><div key={t} className={'og-module '+(i===answers.length?'selected':'')}><span>{i<answers.length?'✓':i+1}</span>{t}<small>{i<answers.length?'已记录':i===answers.length?'进行中':''}</small></div>)}<div className="mt-6 border-t border-slate-200 pt-5 text-sm text-slate-500"><strong className="text-slate-700">{form.direction}</strong><p>{form.intake} · {form.rank}</p><button className="og-link" onClick={()=>go('match')}>修改基础信息</button></div></aside><section className="og-chat"><div className="og-chat-head"><div><span className="og-ai">O</span><strong>申请访谈教练 <small className="og-chat-progress">{Math.min(answers.length+1,5)} / 5</small></strong><span className="tag">模拟模式</span></div><button className="og-link" onClick={saveExit}>保存并退出</button></div><div className="og-messages" ref={feed} role="log" aria-live="polite"><div className="og-bubble ai">你好，我们会用 5 个话题梳理申请素材。你可以写短句；没有的经历直接说“暂无”，不会替你编造。</div>{Array.from({length:Math.min(answers.length+1,5)},(_,i)=><React.Fragment key={i}><div className="og-question-label">{String(i+1).padStart(2,'0')} · {titles[i]}</div><div className="og-bubble ai">{question(i,form)}</div>{answers[i]&&<><div className="og-bubble user">{answers[i]}</div><button className="og-edit-answer" onClick={()=>{setInput(answers[i]);setAnswers(a=>a.slice(0,i));setBusy(false);clearTimeout(timer.current)}}>从这条重新回答（后续回答将清空）</button></>}</React.Fragment>)}{busy&&<div className="text-sm text-slate-500 py-2">正在记录你的回答…</div>}{hasProfile&&!busy&&<div className="og-chat-complete"><strong>五个话题已记录，档案可以生成了。</strong><p>下一步会保留你的原始表述，并标出需要确认的部分。</p><button className="btn primary" onClick={()=>go('profile')}>生成我的申请档案</button></div>}</div>{!hasProfile&&<form className="og-composer" onSubmit={send}><label className="sr-only" htmlFor="answer">你的回答</label><textarea id="answer" maxLength={4000} value={input} onChange={e=>setInput(e.target.value)} placeholder={answers.length===1?'可以按“背景：\n任务：\n行动：\n结果：”分行填写，也可直接讲述。':'讲讲你的经历，或写“暂无，待补充”…'} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')send(e)}}/><div className="flex items-center justify-between gap-3"><button type="button" className="og-link" onClick={()=>setInput(sampleAnswers[answers.length])}>使用虚构示例回答</button><span className="text-xs text-slate-400 hidden sm:block">Ctrl / ⌘ + Enter 发送</span><button className="btn primary" disabled={!input.trim()||busy} type="submit">发送回答</button></div></form>}</section></div></>}</>}
{route==='profile'&&<>{!hasProfile?<Empty text="完成五个访谈话题后，即可生成你的申请档案。" go={()=>go(form.school?'interview':'match')}/>:<><div className="og-title flex flex-wrap justify-between gap-4 items-end"><div><span className="og-kicker">03 / YOUR APPLICATION PROFILE</span><h1>你的经历，开始有了清晰的轮廓。</h1><p>一份可确认、可补充、可用于下一步申请的素材档案。</p></div><button className="btn" onClick={saveExit}>保存并退出</button></div><Banner/><div className="grid md:grid-cols-2 gap-6"><ProfileCard n="01" title="硬背景" tag="来自基础表单" action="修改基础信息" onClick={()=>go('match')}><dl className="og-facts">{[['本科学校',form.school],['专业',form.major],['均分 / GPA',form.grade],['语言',form.language],['GMAT / GRE',form.tests],['入学季',form.intake],['目标方向',form.direction],['排名 / 城市',form.rank+' / '+form.city],['跨专业',form.cross],['实习 / 科研',form.internships+' / '+form.research]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></ProfileCard><ProfileCard n="02" title="经历素材库" tag="规则整理 · 待本人确认" action="一键导入文书工作台" onClick={()=>{setDraft(outline());go('coach')}}><div className="flex gap-2 mb-4"><span className="tag">#{form.direction.split(' · ')[0]}</span><span className="tag">#课程项目</span></div><div className="og-star">{star().map(([k,v],i)=><div key={k}><b>{'STAR'[i]}</b><div><strong>{k}</strong><p>{v}</p></div></div>)}</div><details className="og-details"><summary>查看原始项目经历及其他素材</summary><p>{answers[1]}</p><h4>实习 / 科研 / 其他</h4><p>{answers[2]}</p><h4>个人贡献与成长</h4><p>{answers[3]}</p></details></ProfileCard><ProfileCard n="03" title="动机与规划" tag="保留你的原始表述" action="生成 PS 核心提纲" onClick={()=>openService('outline')}><h4 className="og-mini-heading">为什么继续学习</h4><p className="og-raw">{answers[0]}</p><h4 className="og-mini-heading">短期目标 / 长期方向 / 能力缺口</h4><p className="og-raw">{answers[4]}</p><p className="text-sm text-slate-500 mt-5">尚未区分目标层次的部分，可回到访谈继续补充。</p></ProfileCard><ProfileCard n="04" title="初步定位评估" tag="非录取预测" action="查看选校与时间线建议" onClick={()=>openService('schools')}><p className="text-slate-600 mb-4">目标：{form.intake} · {form.rank} · {form.direction}</p>{[['冲刺','待评估','需要项目竞争程度与完整背景信息。'],['匹配','待核对','逐项核对学位、先修课和语言要求。'],['保底','不强行推荐','当前有限项目库无法支持可靠保底判断。']].map(([a,b,c])=><div className="og-assessment" key={a}><b>{a}</b><div><strong>{b}</strong><p>{c}</p></div></div>)}<div className="mt-5"><button className="og-link" onClick={()=>openService('timeline')}>生成申请时间线</button></div></ProfileCard></div><div className="og-bottom-strip"><p>档案由你的输入构成。没有提及的成绩、成果和经历不会自动补写。</p><button className="btn" onClick={()=>go('interview')}>回顾 / 修改访谈</button></div></>}</>}
{route==='advice'&&<>{!hasProfile?<Empty text="先完成档案，才能把建议与你的素材连接起来。" go={()=>go('match')}/>:<><div className="og-title"><span className="og-kicker">04 / TURN INSIGHT INTO ACTION</span><h1>把档案，变成下一步行动。</h1><p>围绕 {form.direction}，整理选校线索、准备顺序和文书结构。</p></div><Banner/><div className="og-tabs" role="tablist" aria-label="建议类型">{[['schools','选校建议'],['timeline','申请时间线'],['outline','PS 核心提纲']].map(([id,t])=><button key={id} role="tab" aria-selected={service===id} onClick={()=>setService(id)}>{t}</button>)}</div><section className="og-panel" role="tabpanel">{service==='schools'&&<><h2>先核对要求，再判断定位</h2><p className="text-slate-500 mt-3">以下为前端规则演示，不根据 GPA 推算录取机会。项目库目前仅覆盖少量 EE 项目。</p>{form.direction.startsWith('EE')?<><div className="grid md:grid-cols-2 gap-5 mt-6">{[['电气与电力方向','核对电力系统、控制、数学等先修内容；结合你的课程和项目记录说明准备程度。'],['电子与通信方向','核对通信及信号处理基础，不能仅凭“电子电气”专业名称确认满足要求。']].map(([t,d])=><div className="og-service-card" key={t}><span className="tag">待核对</span><h3>{t}</h3><p>{d}</p></div>)}</div><a className="btn primary mt-6" href="#programs">结合官网资料浏览项目</a></>:<div className="og-empty-inline">当前项目库尚未覆盖 {form.direction}，不会将 EE 项目作为匹配结果。可以先完成档案与文书素材整理。</div>}<div className="og-raw mt-6"><h4>你提供的学术动机</h4>{answers[0]}</div></>}{service==='timeline'&&<><h2>{form.intake} · 申请准备路线</h2><p className="text-slate-500 mt-2">按阶段安排，不虚构截止日期。学校正式时间和各项目材料清单需分别核对。</p><div className="og-roadmap">{[['现在','核对方向与先修课',`对照 ${form.direction} 的目标项目，把成绩单和课程说明整理好。`],['选定项目后','建立每个项目的材料清单','区分PS题目、篇幅和推荐信数量，不使用一份通用清单替代。'],['提交前','分别完成文书与推荐流程','用档案中的真实经历准备材料，再核对官网截止日期。'],['提交后','跟踪通知与后续条件','根据学校通知记录补件、结果和接受录取的期限。']].map(([a,b,c])=><div key={a}><span>{a}</span><div><h3>{b}</h3><p>{c}</p></div></div>)}</div><a className="btn primary" href="#applications">打开按项目管理的工作台</a></>}{service==='outline'&&<><h2>PS 核心提纲</h2><p className="text-slate-500 mt-2">将你的原始素材放入提纲，不代写、不虚构项目匹配。具体字数与题目仍需查看官网。</p><pre className="og-outline">{outline()}</pre><button className="btn primary" onClick={()=>{setDraft(outline());go('coach')}}>导入文书工作台</button></>}</section><button className="og-link mt-6" onClick={()=>go('profile')}>返回我的申请档案</button></>}</>}
{toast&&<div className="og-toast" role="status">{toast}</div>}</div>
}
function Empty({text,go}){return <div className="og-panel text-center py-16"><h2>让我们从你的背景开始</h2><p className="my-5 text-slate-500">{text}</p><button className="btn primary" onClick={go}>继续建档</button></div>}
function ProfileCard({n,title,tag,action,onClick,children}){return <section className="og-panel flex flex-col"><div className="og-profile-heading"><span>{n}</span><div><h2>{title}</h2><small>{tag}</small></div></div><div className="flex-1">{children}</div><button className="btn mt-6 self-start" onClick={onClick}>{action}</button></section>}
function Legacy({route,refresh,draft}){const ref=useRef(null);useEffect(()=>{ref.current.innerHTML=(window.legacyViews[route]||window.legacyViews.home)();if(route==='coach'&&draft){const box=ref.current.querySelector('#ps');box.value=draft;box.dispatchEvent(new Event('input',{bubbles:true}));const note=document.createElement('p');note.className='notice';note.textContent='已从申请档案导入提纲。这是你的素材整理，不是针对当前项目生成的成稿；请核对项目要求。';box.before(note)}},[route,refresh,draft]);return <div ref={ref}/>}
createRoot(document.getElementById('app')).render(<App/>);
