import React,{useEffect,useMemo,useRef,useState} from 'react';
import {programs} from '../library/data.js';
import './coach.css';

const targetPrograms=programs.filter(p=>/PS/i.test(p.materials));
const seedText=`My interest in telecommunications began with a fictional undergraduate project about monitoring signal quality across a small campus network. Our first prototype worked only when the devices were close together. I became curious about what happened between a transmitted signal and the information received at the other end. Instead of treating the dropped packets as a simple coding error, I started comparing the effect of distance, interference and antenna position. That experience made communication systems feel like a connected engineering problem: the performance of a network depends on the choices made at every layer.

My undergraduate studies have given me a foundation in electronic engineering, mathematics and programming. In a fictional Signals and Systems module, I learned to represent continuous and discrete signals and to interpret frequency-domain behaviour. A digital communications class introduced modulation, channel effects and error control. I have also used Python to organise experimental data and visualise changes between test conditions. These experiences taught me to check assumptions before drawing conclusions. When a result looked unexpected, I returned to the measurement setup, repeated the test and recorded the conditions rather than selecting only the data that supported my first idea.

For a fictional wireless sensor project, my team built a basic prototype to send temperature readings between two rooms. I was responsible for comparing packet loss at different distances and documenting the test procedure. The first set of results varied because the receiver was moved between trials. I suggested fixing its position, repeating each measurement and logging the surrounding conditions. The revised tests were more consistent and helped us distinguish a weak signal from an inconsistent method. I contributed the measurement plan and analysis, while the circuit and software were developed collaboratively. The project strengthened my interest in reliable communication and showed me how practical validation can improve a technically simple system.

I am applying to the Telecommunications MSc at UCL because I want to study communication systems and networks in greater depth. The programme’s coverage of communication technologies, network design and data networks is relevant to the questions that emerged from my project. I would like to connect theoretical understanding with the evaluation of real systems, particularly how design decisions affect reliability and performance. Before submitting, I will verify the current module list and explain which parts best support my goals. I am also interested in learning with students whose technical backgrounds and experiences differ from mine, because network problems benefit from more than one perspective.

After the degree, my short-term goal is to begin in a communications or network engineering role where I can contribute to testing, performance analysis and system development. Over time, I hope to take responsibility for designing more dependable connected systems. I know that I still need stronger preparation in advanced communication theory and network architecture. Postgraduate study would give me a structured opportunity to build that knowledge and practise applying it. My project experience has not made me an expert, but it has shown me how I learn: define a measurable question, make a careful test, and revise my explanation when the evidence changes. I hope to bring that approach to further study and future engineering work.

I believe that this course will be a very important step in my life. UCL is an excellent university with a strong reputation, and I am confident that studying there will allow me to achieve my dreams. I am hardworking, passionate and motivated to make a positive contribution to society. I look forward to the opportunity to learn from leading academics and to develop the skills required for a successful career in the modern world.`;

const assets=[
 {icon:'🎓',group:'硬背景',title:'本科与学业概况',tag:'#电子信息工程',body:'海川理工大学（虚构） · 本科电子信息工程 · 均分 82/100',insert:'My undergraduate studies in electronic information engineering gave me a foundation in signals, systems and programming. My current average is 82/100 at Haichuan Institute of Technology (a fictional example).'},
 {icon:'📡',group:'经历弹药库',title:'无线传感课程项目',tag:'#通信系统  #测试分析',body:'S 课程项目需要比较无线节点的传输稳定性。T 我负责规划测试并分析丢包。A 固定接收端位置、重复测量、记录环境条件。R 虚构示例：复测结果更稳定，团队据此识别出距离与干扰的影响。',insert:'In a fictional wireless sensor project, I planned repeatable tests for packet loss, fixed the receiver position and recorded environmental conditions. This helped our team distinguish signal effects from variation in the test setup.'},
 {icon:'🎯',group:'动机与规划',title:'学习动机与职业目标',tag:'#网络工程  #可靠系统',body:'短期：从事通信或网络工程中的测试与性能分析。长期：参与设计更可靠的互联系统。希望补足：高级通信理论与网络架构。',insert:'My short-term goal is to contribute to testing and performance analysis in a communications or network engineering role. Over time, I hope to help design more dependable connected systems, supported by stronger knowledge of communication theory and network architecture.'}
];
const referenceFields=[['推荐人信息','推荐人姓名、职称、与你的关系及认识时长'],['课程表现','课程名称、课堂参与、作业或项目表现'],['科研 / 实习能力','推荐人亲自观察到的任务、行动与能力证据'],['综合推荐','适合申请的方向、成长空间及推荐意见']];
const cvRows=[['2025.09 – 2026.06','无线传感课程项目','测试计划 · Python · 信号分析'],['2024.09 – 2025.06','电子工程实验课程','电路测量 · 数据整理 · 团队协作'],['2023.09 – 2024.06','校内技术社团（虚构）','设备维护 · 活动支持']];
const countWords=s=>(s.match(/[A-Za-z0-9]+(?:['’.-][A-Za-z0-9]+)*/g)||[]).length;
function readLocalDraft(){try{return JSON.parse(localStorage.getItem('offergo-coach-demo')||'null')}catch{return null}}

export default function Coach({draft='',notify=()=>{}}){
 const [savedDraft]=useState(readLocalDraft);
 const [target,setTarget]=useState(()=>savedDraft?.target??targetPrograms[0]?.id??'');
 const [type,setType]=useState(()=>savedDraft?.type||'ps');
 const [text,setText]=useState(()=>savedDraft?.text||seedText);
 const [selected,setSelected]=useState('');
 const [fontSize,setFontSize]=useState('16');
 const [diagnosed,setDiagnosed]=useState(false);
 const [details,setDetails]=useState(false);
 const [inserting,setInserting]=useState(false);
 const [fields,setFields]=useState(()=>savedDraft?.fields||Object.fromEntries(referenceFields.map(([k])=>[k,''])));
 const [rows,setRows]=useState(()=>savedDraft?.rows||cvRows);
 const editor=useRef(null);
 const selection=useRef({start:0,end:0});
 const program=useMemo(()=>programs.find(p=>p.id===Number(target))||targetPrograms[0],[target]);
 const maxWords=program?.id===1?500:1000;
 const words=countWords(text);
 const isOver=type==='ps'&&words>maxWords;
 useEffect(()=>{if(draft?.trim())setText(draft)},[draft]);

 function syncSelection(){const el=editor.current;if(!el)return;selection.current={start:el.selectionStart,end:el.selectionEnd};const phrase=el.value.slice(el.selectionStart,el.selectionEnd).trim();if(phrase.length>6)setSelected(phrase);else if(!phrase)setSelected('')}
 function insertAsset(item){
   if(type!=='ps'){notify(type==='cv'?'素材插入 PS 编辑器；请在简历时间线中编辑对应经历。':'素材插入 PS 编辑器；推荐信内容请以推荐人亲自观察为准。');return}
   const el=editor.current;if(!el)return;const {start,end}=selection.current;const before=text.slice(0,start),after=text.slice(end);const spacer=before&& !before.endsWith('\n')?'\n\n':'';const insertion=(spacer?spacer:'')+item.insert+'\n\n';const next=before+insertion+after;setText(next);setInserting(true);setTimeout(()=>{el.focus();const caret=before.length+insertion.length;el.setSelectionRange(caret,caret);selection.current={start:caret,end:caret};setInserting(false)},45);notify('已把虚构素材插入编辑器，可继续核对和修改。');
 }
 function applyFormat(kind){if(type!=='ps'){notify('格式工具当前用于 PS 编辑器。');return}const el=editor.current;if(!el)return;const {start,end}=selection.current;const chunk=text.slice(start,end)||'选中文本';let replacement=kind==='bold'?`**${chunk}**`:kind==='italic'?`_${chunk}_`:chunk.split('\n').map(line=>line?`• ${line}`:'').join('\n');const next=text.slice(0,start)+replacement+text.slice(end);setText(next);setTimeout(()=>{el.focus();el.setSelectionRange(start,start+replacement.length);selection.current={start,end:start+replacement.length}},0)}
 function save(){try{localStorage.setItem('offergo-coach-demo',JSON.stringify({type,target,text,fields,rows}));notify('草稿已保存在此浏览器中；没有上传。')}catch{notify('当前浏览器无法保存，请保持页面打开。')}}
 function diagnose(){setDiagnosed(true);notify('已显示基于规则的反馈示例；尚未接入真实 AI。')}
 function setField(name,value){setFields(v=>({...v,[name]:value}))}
 function importCv(){setRows(v=>[['2026.01 – 2026.06','无线传感课程项目（虚构档案）','测试计划 · Python · 信号分析'],...v]);notify('已将虚构档案经历加入简历时间线。')}
 const selectedExcerpt=selected?selected.slice(0,185)+(selected.length>185?'…':''):'未选择段落。点击或拖选编辑器中的文字，查看针对该段的反馈。';

 return <div className="coach-page">
  <div className="coach-topline"><div><span className="coach-eyebrow">PERSONAL STATEMENT STUDIO</span><h1>文书工作台</h1></div><div className="coach-context"><label>选择目标项目<select aria-label="选择目标项目" value={target} onChange={e=>setTarget(e.target.value)}>{targetPrograms.map(p=><option key={p.id} value={p.id}>{p.school} · {p.english}</option>)}</select></label><label>选择文书类型<select aria-label="选择文书类型" value={type} onChange={e=>setType(e.target.value)}><option value="ps">Personal Statement</option><option value="cv">CV / 简历</option><option value="reference">推荐信</option></select></label></div></div>
  <div className="coach-context-note"><span>项目要求联动</span><p>当前通信项目需 PS；项目库中的两个曼彻斯特项目不要求 PS，因此不列入此处。</p><a href="#program/" onClick={e=>{e.preventDefault();location.hash='program/ucl-telecommunications'}}>查看项目档案</a></div>
  <div className="coach-layout">
   <aside className="coach-assets"><div className="coach-section-heading"><div><span>YOUR STORY, ORGANIZED</span><h2>我的档案素材库</h2></div><span className="coach-demo-badge">虚构演示</span></div><div className="coach-profile-chip"><span>林</span><div><strong>林同学 · 示例档案</strong><small>电子信息工程 · 海川理工大学</small></div></div><div className="coach-assets-list">{assets.map((a,i)=><article className="coach-asset" key={a.title}><div className="coach-asset-head"><span>{a.icon}</span><div><small>{a.group}</small><strong>{a.title}</strong></div></div><p>{a.body}</p><div className="coach-asset-foot"><span>{a.tag}</span><button onClick={()=>insertAsset(a)} aria-label={`插入素材：${a.title}`}>＋ 插入</button></div></article>)}</div><div className="coach-asset-tip">素材来自虚构演示档案。正式使用时，请由本人核实每一项经历和数据。</div></aside>
   <section className="coach-editor-panel"><div className="coach-editor-heading"><div><span className="coach-eyebrow">DRAFT · {program?.name||'目标项目'}</span><h2>{type==='ps'?'个人陈述':type==='cv'?'简历时间线':'推荐信结构'}</h2></div><span className="coach-local-tag">仅本机演示</span></div>
    {type==='ps'?<><div className="coach-toolbar" role="toolbar" aria-label="文书格式工具"><label>字号<select aria-label="字号" value={fontSize} onChange={e=>setFontSize(e.target.value)}><option value="15">15</option><option value="16">16</option><option value="18">18</option><option value="20">20</option></select></label><i/><button onClick={()=>applyFormat('bold')} aria-label="加粗" title="加粗"><b>B</b></button><button onClick={()=>applyFormat('italic')} aria-label="斜体" title="斜体"><em>I</em></button><button onClick={()=>applyFormat('list')} aria-label="列表" title="列表">☷</button><span className="coach-word-count"><strong className={isOver?'over':''}>{words}</strong> / {maxWords} 词</span></div><textarea id="ps" ref={editor} className={`coach-textarea ${inserting?'inserting':''}`} aria-label="个人陈述编辑器" style={{fontSize:`${fontSize}px`}} value={text} onChange={e=>setText(e.target.value)} onSelect={syncSelection} onMouseUp={syncSelection} onKeyUp={syncSelection} spellCheck="false" placeholder="从一段真实经历开始，说明它怎样影响了你的学术兴趣。"/><div className="coach-editor-footer"><span>{isOver?'已超过项目示例字数上限，建议精简。':'选中段落后，右侧将切换为对应分析。'}</span><div><button className="coach-button secondary" onClick={save}>保存草稿</button><button className="coach-button primary" onClick={diagnose}>提交诊断</button></div></div></>:type==='reference'?<div className="coach-structured">{referenceFields.map(([label,hint])=><label className="coach-structured-field" key={label}><span>{label}</span><small>{hint}</small><textarea value={fields[label]} onChange={e=>setField(label,e.target.value)} placeholder="仅整理推荐人亲自了解、愿意确认的事实。"/></label>)}<div className="coach-editor-footer"><span>推荐信应由推荐人审阅并确认。</span><div><button className="coach-button secondary" onClick={save}>保存草稿</button><button className="coach-button primary" onClick={diagnose}>查看结构建议</button></div></div></div>:<div className="coach-cv"><div className="coach-cv-toolbar"><span>时间线 · 从档案导入后再逐项确认</span><button onClick={importCv}>＋ 从档案导入经历</button></div><div className="coach-cv-table"><div className="coach-cv-row head"><span>时间</span><span>经历 / 项目</span><span>关键词与成果</span><span></span></div>{rows.map((row,i)=><div className="coach-cv-row" key={i}>{row.map((cell,j)=><input key={j} aria-label={`第${i+1}条经历，第${j+1}列`} value={cell} onChange={e=>setRows(v=>v.map((r,k)=>k===i?r.map((c,n)=>n===j?e.target.value:c):r))}/>) }<button aria-label={`删除第${i+1}条经历`} onClick={()=>setRows(v=>v.filter((_,k)=>k!==i))}>×</button></div>)}</div><div className="coach-editor-footer"><span>虚构示例 · 请替换为本人核实后的经历。</span><div><button className="coach-button secondary" onClick={save}>保存草稿</button><button className="coach-button primary" onClick={diagnose}>检查结构</button></div></div></div>}
    <div className="coach-ethics">AI 只提供反馈和教练，不代写，不虚构经历。当前页面使用本机静态示例，不会上传内容。</div>
   </section>
   <aside className="coach-feedback"><div className="coach-feedback-title"><div><span>ADMISSIONS COACH</span><h2>AI 招生官视角</h2></div><span className="coach-spark">✦</span></div><div className="coach-score-card"><div className="coach-score-ring" role="img" aria-label="项目匹配度演示评分82%"><div><strong>82%</strong><small>匹配度演示</small></div></div><div><strong>项目匹配度</strong><p>{program?.name||'目标项目'} · 静态评分示例</p><small>不是录取概率，也不是实际 AI 评估</small></div></div>
    {selected?<div className="coach-selection-card"><span>正在分析所选段落</span><p>“{selectedExcerpt}”</p><small>选中内容变化时，此反馈随之切换。</small></div>:null}
    <div className="coach-feedback-list" key={`${selected?'selected':'whole'}-${isOver}-${diagnosed}`}><article className="coach-feedback-card warning"><span>⚠</span><div><strong>{isOver?'长度风险':'篇幅检查'}</strong><p>{isOver?`当前约 ${words} 词，超过 ${program?.school==='伦敦大学学院'?'UCL 示例要求的 500':'项目示例'}词数。可优先删去泛化结尾，并保留经历证据。`:'稿件暂未超过示例字数限制。正式字数与题目请以项目官网为准。'}</p></div></article><article className="coach-feedback-card logic"><span>✦</span><div><strong>{selected?'选中段落分析':'逻辑连贯性'}</strong><p>{selected?'该段需要明确它如何支撑申请动机，并与下一段的学习目标建立具体联系。':'第二段提到职业目标时，前文可补一条对应的课程或项目证据，形成动机到规划的连接。'}</p></div></article><article className="coach-feedback-card template"><span>⌕</span><div><strong>模板化检测</strong><p>{selected?'当前选段中可以减少泛化表达，改用具体行动、观察或结果。':'结尾的“优秀大学、实现梦想”等表达较通用。建议用档案中可核实的项目观察切入。'}</p></div></article></div>
    {diagnosed&&<div className="coach-diagnosis-note">示例诊断已更新：请先核对项目要求，再保留能证明动机与能力的真实细节。</div>}
    <button className="coach-detail-button" onClick={()=>setDetails(v=>!v)}>{details?'收起详细批注':'查看详细批注'} <span>{details?'−':'＋'}</span></button>{details&&<div className="coach-detail-list"><h3>逐段修改方向</h3><p><b>开头：</b>从具体问题或经历入手，避免先写学校声誉。</p><p><b>经历：</b>写清个人承担部分，并让结果可被解释。</p><p><b>项目匹配：</b>核对课程后，再说明与能力缺口的联系。</p></div>}
   </aside>
  </div>
  <div className="coach-bottom-note"><span>不确定素材是否准确？</span><p>先回到档案核实，再将内容用于申请材料。</p><a href="#profile">查看申请档案</a><span className="coach-bottom-disclaimer">AI 只提供反馈和教练，不代写，不虚构经历。</span></div>
 </div>
}
